### ISSUE TITLE
no posibility to open issues in your repo.: Ilawy/gtts

### ISSUE THREAD

**Issue by gustawdaniel** [Ilawy/to-do#1]
in repo https://github.com/Ilawy/gtts i can't open issue

but there is bug described in https://github.com/dunosaurs/color/issues/9

Todo:
- [x] add issues to gtts repo
- [x] fix bug in import

**Comment by Ilawy** [comment]
Thanks for reporting, I've opened issues there
the issue will be solved as soon as possible

**Comment by Ilawy** [comment]
Hello @gustawdaniel, I've updated the readme import source, please tell me if you still have a problem using the package

**Comment by gustawdaniel** [comment]
I tested

```
import gtts from "@ilawy/gtts";

const speechFile = "./demo-gtts.wav";

async function main() {
  const buffer: Uint8Array = await gtts("13", {
    language: "de",
  });
  await Deno.writeFile(speechFile, buffer);
}
main();
```

and it works perfectly. Thanks.
